success:
  code: "0000"
  statusCode: "200"
  th: "สำเร็จ"
  en: "success"

template:
  code: "9999"
  th: "%s"
  en: "%s"

# start with 99xx
internal:
  general:
    code: "9900"
    th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
    en: "System cannot process this request at the moment. Please try again later."
  bad_request:
    code: "9901"
    th: "คำขอไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"
    en: "Bad request. Please try again later."
  internal_server_error:
    code: "9903"
    th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
    en: "System cannot process this request at the moment. Please try again later."
  database_error:
    code: "9904"
    th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
    en: "System cannot process this request at the moment. Please try again later."
  timeout:
    code: "9905"
    th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
    en: "System cannot process this request at the moment. Please try again later."
  request_limit:
    code: "9906"
    th: "คำร้องถึงปริมาณจำกัด โปรดทำรายการใหม่ภายหลัง"
    en: "Requests are exceed the limit. Please try again later."
  permission_denied:
    code: "9908"
    th: "ไม่มีสิทธิ์เข้าถึงข้อมูล"
    en: "You do not have permission."
  system_maintenance:
    code: "9909"
    th: "ระบบปิดปรับปรุง"
    en: "System under maintenance."
