server_setting:
  run_mode: "debug"
  allow_origins:
    - "http://localhost:"
  access_secret: ""
  refresh_secret: ""
  token_lifetime_minutes: 12h
  diff_timestamp: 15m
  domain: "https://test.pbank.com"
  max_file_size: 10485760
  ping_message: "ping [loadtest]"
  path:
    qr_code: "/scanQRCode"

mongo_driver:
  db:
    schema: ""
    url: ""
    write_majority_count: 2

redis:
  redis_prefix: "pbank_loadtest"
  pool_size: 1000
  pool_timeout: 30
  min_idle_conns: 100
  max_idle_conns: 500
  write_timeout: 10
  read_timeout: 10
  dial_timeout: 10
  max_conn_lifetime: 5
  common:
    addr: ""
    port: ""
    password: ""

elastic_search:
  templates_dir: "template/elasticsearch"
